### ISSUE TITLE
No save button when adding a new gototraining session

### ISSUE THREAD

**Issue by alanrobinson5538** [alokr912/moodle-mod_gotowebinar#1]
[Doc1.docx](https://github.com/alokr912/moodle-mod_gotowebinar/files/1555249/Doc1.docx)
Hi, I've added your plugin to integrate with gototraining.

I've added a new course, and chosen the activity as gotowebinar.

When adding a date and timed session there is no save button, only a cancel.  Please see screen shots.

Thanks

Alan

**Comment by alokr912** [comment]
Hi Alan,

What is the version of Moodle that  you are using?

Regards,
Alok

**Comment by alanrobinson5538** [comment]
Hi Alok

It’s 3.1.9, I know this plugin is for Moodle 2, but I was hoping it would be something simple…

Alan


Alan Robinson
Royal Berkshire NHS Foundation Trust
Business Change Training Lead
Telephone:  0118 322 6940
Mobile 07853 646463

**Comment by alokr912** [comment]
I have not tested it  with Moodle 3.1 , I will test and update all branch by Monday(18-Dec).

**Comment by alanrobinson5538** [comment]
That’s brilliant, thank you…..



Alan Robinson
Royal Berkshire NHS Foundation Trust
Business Change Training Lead
Telephone:  0118 322 6940
Mobile 07853 646463

**Comment by alokr912** [comment]
Hi Alan,

I have tested it for moodle 2.7, 2.8, 2.9, 3.0, 3.1, 3.2 and 3.3 . 
Please download the relevant branch to your moodle

**Comment by alanrobinson5538** [comment]
Hi Alok

I’ve got Moodle 3.4 up and running and have used the gotowebinar plugin.

It installs absolutely fine, and is available as a module in the drop down for activity type.

However, when I’m adding a session in the plugin (see screenshot) there is no SAVE button, only cancel.


[cid:image001.png@01D39F6B.E02E3CC0]



[cid:image002.png@01D39F6B.E02E3CC0]
Can you help please?

Thanks

Alan



Alan Robinson
Royal Berkshire NHS Foundation Trust
Business Change Training Lead
Telephone:  0118 322 6940
Mobile 07853 646463

**Comment by alokr912** [comment]
Hi Alan,
The above plugin support only till  moodle 3.3, very soon i will release the this plugin for Moodle 3.4
