### ISSUE TITLE
Issue with moodle 3.6.1

### ISSUE THREAD

**Issue by Humzabelin** [alokr912/moodle-mod_gotowebinar#27]
Hello alokr912
we try to install your plug but we get attached error:
Warning: Illegal string offset 'request' in /var/www/academy/moodle/mod/gotowebinar/lib/OSD.php on line 316

Debug info:
Error code: generalexceptionmessage
Stack trace:
line 190 of /mod/gotowebinar/lib/OSD.php: OSDError thrown
line 73 of /mod/gotowebinar/lib/OSD.php: call to OSD::request()
line 52 of /mod/gotowebinar/configtest.php: call to OSD::authenticate_with_password()

when we try to make the test connection.
We installed last your version.
Please how can we fix it?
Thank you very much.

Kind Regards

Umberto

**Comment by alokr912** [comment]
I will check it

**Comment by Humzabelin** [comment]
Thank you so much Alok.
We are installing it on customer environment and we are in trouble.
Let me know how we can help you or details you need.
Thank you
Umb

**Comment by abhishekumarai1** [comment]
Hi Umb,

I have made changes for OAuth 2.O,
Please test and let me know if you have any issue.

**Comment by Humzabelin** [comment]
Hi Alok,
we installed it and it works fine.
Thank you very much indeed.
Have nice day.

Umb
