### ISSUE TITLE
Recordings

### ISSUE THREAD

**Issue by relecand** [alokr912/moodle-mod_gotowebinar#32]
Hi Alok,

thank you for this plugin!

Would it be possible to list the recorded webinar sessions within the view.php?

Here you prepared it already:
https://github.com/alokr912/moodle-mod_gotowebinar/blob/master/view.php#L97

The API Reference for the recording is here:
https://goto-developer.logmeininc.com/content/gotowebinar-api-reference-v2#/RecordingAssets/searchAssets

All the best,

Christian

**Comment by alokr912** [comment]
API is available, will add it in future.

**Comment by relecand** [comment]
Would be great! Thank you!
