### ISSUE TITLE
Error on server

### ISSUE THREAD

**Issue by kurtius-zz** [alokr912/moodle-mod_gotowebinar#34]
Hi, I'm trying to configure your mod, but the test doesn't return any message, on server I found this errors:

[Fri Jan 17 18:23:36 2020] [warn] [client 151.28.194.51] mod_fcgid: stderr: PHP Parse error: syntax error, unexpected '=' in /var/www/vhosts/enpab.it/subdomains/fad/mod/gotowebinar/configtest.php on line 48 
[Fri Jan 17 18:25:06 2020] [warn] [client 151.28.194.51] mod_fcgid: stderr: PHP Parse error: syntax error, unexpected 'echo' (T_ECHO) in /var/www/vhosts/enpab.it/subdomains/fad/mod/gotowebinar/configtest.php on line 49 
[Fri Jan 17 18:25:10 2020] [warn] [client 151.28.194.51] mod_fcgid: stderr: PHP Parse error: syntax error, unexpected 'echo' (T_ECHO) in /var/www/vhosts/enpab.it/subdomains/fad/mod/gotowebinar/configtest.php on line 49 

Can you please help me? thanks

**Comment by alokr912** [comment]
Please  take from appropriate branch as per your Moodle version

**Comment by kurtius-zz** [comment]
with my moodle version (2.9), the only branch that passes the test is the "master" one, but when I try to add the activity the error is "Using $this when not in object context" and on the log it tells me:  error 404 | GET /course/modedit.php?add=gotowebinar&type=&course=13&section=0&return=0&sr=0 HTTP/1.1

can you please help me? thanks!

**Comment by alokr912** [comment]
Kindly pull it from MOODLE_29_STABLE

**Comment by kurtius-zz** [comment]
with 29 release does not pass the test, without retrieving any error unfortunately.
